name: CDK Deploy on AWS

on:
    push:
        branches:
            - main
      
jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write
        env:
            APP_NAME: ${{ vars.APP_NAME }}
            ACCOUNT_AWS: ${{ vars.ACCOUNT_AWS }}
            REGION_AWS: ${{ vars.REGION_AWS }}
            CERTIFICATE_ARN: ${{ vars.CERTIFICATE_ARN }}
            DOMAIN_NAME: ${{ vars.DOMAIN_NAME }}
            BUILD_DIR: ${{ vars.BUILD_DIR }}
            ROOT_OBJECT: ${{ vars.ROOT_OBJECT }}
            SUBDOMAIN_NAME: ${{ vars.SUBDOMAIN_NAME }}
        steps:
            - name: Checkout Repositorio
              uses: actions/checkout@v4
      
            - name: Instalar .NET
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: ${{ vars.VERSION_DOTNET }}
      
            - name: Instalar Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ vars.VERSION_NODEJS }}
                  
            - name: Update environment.ts file
              run: echo "${{ vars.ENVIRONMENT_TS }}" > "${{ vars.ENVIRONMENT_TS_FILE }}"
                  
            - name: Install Dependencies
              run: npm install
                  
            - name: Build Angular Application
              run: npm run-script build
                  
            - name: Instalar AWS CDK
              run: npm install -g aws-cdk
      
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4
              with:
                  aws-region: ${{ vars.REGION_AWS }}
                  role-to-assume: ${{ vars.ARN_GITHUB_ROLE }}
                  
            - name: CDK Synth
              working-directory: ${{ vars.DIRECTORIO_CDK }}
              run: cdk synth
              
            - name: CDK Deploy
              working-directory: ${{ vars.DIRECTORIO_CDK }}
              run: cdk deploy --require-approval never
          